id: sources

nist:
  csf_xlsx:
    url: "https://csrc.nist.gov/extensions/nudp/services/json/csf/download?olirids=all"
  sp800_53_r5_oscal_json:
    url: "https://raw.githubusercontent.com/usnistgov/oscal-content/main/nist.gov/SP800-53/rev5/json/NIST_SP-800-53_rev5_catalog.json"

ctid:
  attack_to_80053_r5:
    attack_version: "16.1"
    framework_version: "rev5"
    technology_domain: "enterprise"
    url: "https://raw.githubusercontent.com/center-for-threat-informed-defense/mappings-explorer/main/mappings/nist_800_53/attack-16.1/nist_800_53-rev5/enterprise/nist_800_53-rev5_attack-16.1-enterprise.json"

mitre:
  attack_stix:
    enterprise_url: "https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/enterprise-attack/enterprise-attack.json"
    ics_url: "https://raw.githubusercontent.com/mitre-attack/attack-stix-data/master/ics-attack/ics-attack.json"
